# GTEx samples table
samples_tsv: "config/GTEx_samples.tsv"

# path to gdc token file
#gdc_token_file: "config/gdc-user-token.txt"

# assigned temporary directory
local_tmp: "$TMPDIR"

# Remote files to be downloaded to refs/downloads
downloads:
    GRCh38.d1.vd1.fa.tar.gz:
        url: "https://api.gdc.cancer.gov/data/254f697d-310d-4d7d-a27b-27fbf767a834"
        md5: "3ffbcfe2d05d43206f57f81ebb251dc9"
    gencode.v38.annotation.gtf.gz:
        url: "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_38/gencode.v38.annotation.gtf.gz"
        md5: "16fcae8ca8e488cd8056cf317d963407"
    retro.hg38.v1.gtf:
        url: "https://github.com/mlbendall/telescope_annotation_db/raw/master/builds/retro.hg38.v1/transcripts.gtf"
        md5: "c07cf115c1f957b3020efc547f3847fa"
    retro.hg38.v1.tsv.gz:
        url: "https://github.com/mlbendall/telescope_annotation_db/raw/master/builds/retro.hg38.v1/genes.tsv.gz"
        md5: "b3ca6d3705d030742255d216e25dfc1d"

sequences:
    genome: "refs/sequences/genome.fa.gz"
    genome_idx: "refs/sequences/genome.fa.gz.fai"
    genome_dict: "refs/sequences/genome.dict"
    transcripts: "refs/sequences/transcripts.fa"
    transcripts_list: "refs/sequences/transcripts_list.txt"
    transcripts_dupinfo: "refs/sequences/dupinfo.txt"

indexes:
    #kallisto: "refs/index.kallisto/transcripts"
    #bowtie2: "refs/index.bowtie2/genome"
    #hisat2: "refs/index.hisat2/genome"
    star: "refs/index.star/genome"

annotations:
    gencode: "refs/downloads/gencode.v38.annotation.gtf.gz"
    # herv: "refs/downloads/HERV_rmsk.hg38.v2.gtf"
    # l1: "refs/downloads/L1Base.hg38.v1.gtf"
    retro: "refs/annotation/retro.gtf"
    retro_tsv: "refs/annotation/retro.tsv"
    # herv_tsv: "refs/annotation/HERV_rmsk.hg38.v2.tsv"
    # l1_tsv: "refs/annotation/L1Base.hg38.v1.tsv"
    ttg: "refs/annotation/ttg.tsv"
    gsym: "refs/annotation/gsym.tsv"

##### rule-specific resources and parameters #####
# STAR index
sjdbOverhang: 74
star_index_threads: 32
star_index_mem_mb: 40000

# STAR alignment
star_alignment_threads: 32
outFilterMultimapNmax: 500
winAnchorMultimapNmax: 200

# TELESCOPE
telescope_threads: 2

